services:
 db:
  container_name: local-db
  image: mariadb:11.3
  environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
  ports:
      - 3306:3306

 phpmyadmin:
  container_name: local-phpmyadmin
  image: phpmyadmin:5.2
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - PMA_HOST=db
  ports:
    - 8081:80
